# dental-pay-tracker/docker-compose.yml
version: '3.8'

services:
  backend:
    container_name: dental_pay_tracker_backend # <-- AGGIUNGI QUESTO
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - db-data:/app/app
    expose:
      - "5000"
    networks:
      - dental-app-net

  frontend:
    container_name: dental_pay_tracker_frontend # <-- AGGIUNGI QUESTO
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - dental-app-net

networks:
  dental-app-net:
    driver: bridge

volumes:
  db-data: